// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AWSSSOIntegration configures an IAM Identity Center portal.
 */
export interface AWSSSOIntegration {
    "startUrl": string;
    "region": string;

    /**
     * TokenExpires is when the cached access token stops working. Nil when logged out.
     */
    "tokenExpires"?: string | null;
}

/**
 * AWSSession holds AWS specific settings.
 */
export interface AWSSession {
    /**
     * Profile is the name written to ~/.aws/config. Defaults to the session name.
     */
    "profile"?: string;

    /**
     * AccountID and RoleName identify an SSO role or the target of AssumeRole.
     */
    "accountId"?: string;
    "roleName"?: string;

    /**
     * RoleARN is the role to assume. Set for KindAWSAssumeRole.
     */
    "roleArn"?: string;

    /**
     * SourceSessionID provides credentials for AssumeRole.
     */
    "sourceSessionId"?: string;

    /**
     * ExternalID is passed to AssumeRole when set.
     */
    "externalId"?: string;

    /**
     * MFADevice is the serial or ARN of the MFA device for IAM users.
     */
    "mfaDevice"?: string;
}

/**
 * AzureIntegration configures an Entra ID tenant.
 */
export interface AzureIntegration {
    "tenantId": string;

    /**
     * Account is the signed-in user principal name. Empty when logged out.
     */
    "account"?: string;
}

/**
 * AzureSession holds Azure specific settings.
 */
export interface AzureSession {
    "subscriptionId": string;
    "tenantId": string;
}

/**
 * Cloud identifies a cloud provider.
 */
export enum Cloud {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CloudAWS = "aws",
    CloudAzure = "azure",
    CloudGCP = "gcp",
};

/**
 * Credentials are the short-lived secrets a session yields.
 */
export interface Credentials {
    /**
     * AWS fields.
     */
    "accessKeyId"?: string;
    "secretAccessKey"?: string;
    "sessionToken"?: string;

    /**
     * Token is a bearer token for Azure and GCP.
     */
    "token"?: string;
    "expiration"?: string | null;
}

/**
 * GCPIntegration configures a Google account login.
 */
export interface GCPIntegration {
    /**
     * Account is the signed-in Google account email. Empty when logged out.
     */
    "account"?: string;
}

/**
 * GCPSession holds GCP specific settings.
 */
export interface GCPSession {
    "projectId": string;
    "serviceAccount"?: string;
}

/**
 * Integration is an identity source that sessions are discovered from or
 * authenticated through, for example an IAM Identity Center portal.
 */
export interface Integration {
    "id": string;
    "alias": string;
    "cloud": Cloud;
    "awsSso"?: AWSSSOIntegration | null;
    "azure"?: AzureIntegration | null;
    "gcp"?: GCPIntegration | null;
}

/**
 * Kind identifies how a session obtains credentials.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * KindAWSIAMUser uses long-lived access keys stored in the secret store.
     */
    KindAWSIAMUser = "aws-iam-user",

    /**
     * KindAWSAssumeRole calls STS AssumeRole from another AWS session.
     */
    KindAWSAssumeRole = "aws-assume-role",

    /**
     * KindAWSSSORole fetches role credentials from IAM Identity Center.
     */
    KindAWSSSORole = "aws-sso-role",

    /**
     * KindAzure obtains an Entra ID token for a subscription.
     */
    KindAzure = "azure",

    /**
     * KindGCP impersonates a service account with a signed-in user.
     */
    KindGCP = "gcp",
};

/**
 * Session is one identity or role that can be assumed.
 */
export interface Session {
    "id": string;
    "name": string;
    "kind": Kind;
    "region"?: string;

    /**
     * IntegrationID links the session to the integration that authenticates it.
     */
    "integrationId"?: string;
    "status": Status;

    /**
     * Favorite pins the session to the favorites panel.
     */
    "favorite"?: boolean;

    /**
     * Expires is when the current credentials stop working. Nil when inactive.
     */
    "expires"?: string | null;
    "aws"?: AWSSession | null;
    "azure"?: AzureSession | null;
    "gcp"?: GCPSession | null;
}

/**
 * Settings are user preferences that live alongside the workspace.
 */
export interface Settings {
    /**
     * Theme is "system", "light", or "dark".
     */
    "theme": string;

    /**
     * DefaultRegion pre-fills region fields for new AWS sessions.
     */
    "defaultRegion": string;

    /**
     * AssumeRoleMinutes is the requested duration for STS AssumeRole calls.
     */
    "assumeRoleMinutes": number;

    /**
     * HideOnClose keeps the desktop app running in the tray when its window closes.
     */
    "hideOnClose": boolean;

    /**
     * VerboseLogging turns on diagnostic output, the same as ROLLE_DEBUG=1.
     */
    "verboseLogging": boolean;

    /**
     * AutoUpdateOff disables background update checks. Stored inverted so
     * the default (zero value) keeps updates on.
     */
    "autoUpdateOff": boolean;

    /**
     * Terminal picks the terminal app for "Open terminal". Empty means auto.
     */
    "terminal"?: string;

    /**
     * ProxyURL routes every request through one proxy. Empty follows the
     * HTTPS_PROXY environment.
     */
    "proxyUrl"?: string;

    /**
     * CABundle is a PEM file of extra roots, added to the OS trust store.
     */
    "caBundle"?: string;
}

/**
 * Status is the lifecycle state of a session.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusInactive = "inactive",
    StatusActive = "active",
};

/**
 * Workspace is everything Rolle persists, except secrets.
 */
export interface Workspace {
    "version": number;
    "integrations": Integration[] | null;
    "sessions": Session[] | null;

    /**
     * Onboarded is set once the desktop walkthrough completes.
     */
    "onboarded": boolean;

    /**
     * Settings holds user preferences. Nil means defaults.
     */
    "settings"?: Settings | null;
}
