// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    AddAssumeRoleInput,
    AddGCPImpersonationInput,
    ImportResult,
    LeappImportResult,
    StaticKeys
} from "./models.js";
