// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AddAssumeRoleInput describes a new AssumeRole session.
 */
export interface AddAssumeRoleInput {
    "name": string;
    "region": string;
    "roleArn": string;
    "sourceRef": string;
    "externalId": string;
    "profile": string;
}

/**
 * AddGCPImpersonationInput describes a service account impersonation session.
 */
export interface AddGCPImpersonationInput {
    "name": string;
    "integrationRef": string;
    "projectId": string;
    "serviceAccount": string;
}
