// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as awsconfig$0 from "../awsconfig/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

/**
 * AddAssumeRoleInput describes a new AssumeRole session.
 */
export interface AddAssumeRoleInput {
    "name": string;
    "region": string;
    "roleArn": string;
    "sourceRef": string;
    "externalId": string;
    "profile": string;
}

/**
 * AddGCPImpersonationInput describes a service account impersonation session.
 */
export interface AddGCPImpersonationInput {
    "name": string;
    "integrationRef": string;
    "projectId": string;
    "serviceAccount": string;
}

/**
 * ImportResult describes an imported Identity Center portal.
 */
export interface ImportResult {
    "integration": core$0.Integration;

    /**
     * LoggedIn is true when rolle reuses a valid AWS CLI token and discovers roles.
     */
    "loggedIn": boolean;
    "sessions": core$0.Session[] | null;
}

/**
 * LeappImportResult reports what the import recreated from a Leapp workspace.
 */
export interface LeappImportResult {
    "sessions": core$0.Session[] | null;

    /**
     * Skipped lists the sessions the import did not recreate, and the reason.
     */
    "skipped": string[] | null;
}

/**
 * StaticKeys describes the shared credentials file's static keys.
 */
export interface StaticKeys {
    /**
     * Path is the shared credentials file, in display form.
     */
    "path": string;

    /**
     * Profiles hold static keys, in file order, with the values masked.
     */
    "profiles": awsconfig$0.StaticProfile[] | null;
}
