// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    AWSPortal,
    AzureTenant,
    GCPAccount,
    IAMUserKey,
    LeappChainedRole,
    LeappIAMUser,
    LeappWorkspace,
    Result
} from "./models.js";
