// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AWSPortal is an IAM Identity Center portal referenced by the AWS CLI config.
 */
export interface AWSPortal {
    "alias": string;
    "startUrl": string;
    "region": string;
    "profiles": string[] | null;

    /**
     * HasToken means the AWS CLI holds a valid SSO token for this portal.
     */
    "hasToken": boolean;
}

/**
 * AzureTenant is a directory the az CLI has signed in to.
 */
export interface AzureTenant {
    "tenantId": string;
    "account": string;
}

/**
 * GCPAccount is the gcloud Application Default Credentials identity.
 */
export interface GCPAccount {
    "account": string;
}

/**
 * Result is everything found on the machine.
 */
export interface Result {
    "awsPortals": AWSPortal[] | null;
    "azureTenants": AzureTenant[] | null;
    "gcp"?: GCPAccount | null;
}
