// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AWSPortal is an IAM Identity Center portal referenced by the AWS CLI config.
 */
export interface AWSPortal {
    "alias": string;
    "startUrl": string;
    "region": string;
    "profiles": string[] | null;

    /**
     * HasToken means the AWS CLI holds a valid SSO token for this portal.
     */
    "hasToken": boolean;

    /**
     * Source is which tool the portal came from: aws-cli, granted, or leapp.
     */
    "source": string;
}

/**
 * AzureTenant is a directory the az CLI has signed in to.
 */
export interface AzureTenant {
    "tenantId": string;
    "account": string;

    /**
     * Source is which tool the tenant came from: az or leapp.
     */
    "source": string;
}

/**
 * GCPAccount is the gcloud Application Default Credentials identity.
 */
export interface GCPAccount {
    "account": string;
}

/**
 * LeappChainedRole is an AssumeRole session whose source is another session.
 */
export interface LeappChainedRole {
    "name": string;
    "region": string;
    "roleArn": string;
    "parentName": string;
    "profile"?: string;
}

/**
 * LeappIAMUser is an IAM user session from Leapp. Access keys live in the OS
 * keychain under the "Leapp" service, and the import reads them.
 */
export interface LeappIAMUser {
    "id": string;
    "name": string;
    "region": string;
    "mfaDevice"?: string;
    "profile"?: string;
}

/**
 * LeappWorkspace is the subset of a Leapp workspace Rolle can import.
 */
export interface LeappWorkspace {
    "portals": AWSPortal[] | null;
    "tenants": AzureTenant[] | null;
    "iamUsers": LeappIAMUser[] | null;
    "chainedRoles": LeappChainedRole[] | null;

    /**
     * SSORoles counts sessions that Rolle rediscovers by syncing the portal.
     */
    "ssoRoles": number;
}

/**
 * Result is everything found on the machine.
 */
export interface Result {
    "awsPortals": AWSPortal[] | null;
    "azureTenants": AzureTenant[] | null;
    "gcp"?: GCPAccount | null;

    /**
     * Leapp holds sessions from a Leapp workspace that Rolle can recreate.
     */
    "leapp"?: LeappWorkspace | null;
}
