// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeviceLogin is what the user must do to approve a login.
 */
export interface DeviceLogin {
    "verificationUri": string;
    "userCode": string;
}

/**
 * IAMUserInput is the frontend shape for a new IAM user session.
 */
export interface IAMUserInput {
    "name": string;
    "region": string;
    "accessKeyId": string;
    "secretAccessKey": string;
    "mfaDevice": string;
}
