// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfo describes this build and where it keeps its files.
 */
export interface AppInfo {
    "version": string;
    "workspacePath": string;
    "cacheDir": string;
    "awsConfigPath": string;
}

/**
 * DeviceLogin is what the user must do to approve a login. UserCode is empty
 * for the browser flow.
 */
export interface DeviceLogin {
    "verificationUri": string;
    "userCode": string;
}

/**
 * GCPStatus reports whether gcloud Application Default Credentials exist and
 * whether the gcloud CLI itself is available.
 */
export interface GCPStatus {
    "ready": boolean;
    "account": string;
    "loginCommand": string;
    "gcloudFound": boolean;
    "gcloudPath": string;
    "installUrl": string;
}

/**
 * IAMUserInput is the frontend shape for a new IAM user session.
 */
export interface IAMUserInput {
    "name": string;
    "region": string;
    "accessKeyId": string;
    "secretAccessKey": string;
    "mfaDevice": string;
}

/**
 * UpdateInfo is what the settings screen shows after a check.
 */
export interface UpdateInfo {
    "enabled": boolean;
    "currentVersion": string;
    "available": boolean;
    "version"?: string;
    "notes"?: string;
    "state": string;
}
