// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfo describes this build and where it keeps its files.
 */
export interface AppInfo {
    "version": string;
    "workspacePath": string;
    "cacheDir": string;
    "awsConfigPath": string;
}

/**
 * CLIStatus describes whether the rolle command is reachable from a shell.
 */
export interface CLIStatus {
    /**
     * Installed is true when a shell resolves rolle.
     */
    "installed": boolean;

    /**
     * Path is where the command resolves when Installed.
     */
    "path"?: string;

    /**
     * Target is the command inside the app bundle.
     */
    "target"?: string;

    /**
     * Reason is empty when Install can run: "move" when the app runs from a
     * disk image or a temporary location, "unsupported" off macOS bundles.
     */
    "reason"?: string;
}

/**
 * DeviceLogin is what the user must do to approve a login. UserCode is empty
 * for the browser flow.
 */
export interface DeviceLogin {
    "verificationUri": string;
    "userCode": string;
}

/**
 * GCPStatus reports whether gcloud Application Default Credentials exist and
 * whether the gcloud CLI itself is available.
 */
export interface GCPStatus {
    "ready": boolean;
    "account": string;
    "loginCommand": string;
    "gcloudFound": boolean;
    "gcloudPath": string;
    "installUrl": string;
}

/**
 * IAMUserInput is the frontend shape for a new IAM user session.
 */
export interface IAMUserInput {
    "name": string;
    "region": string;
    "accessKeyId": string;
    "secretAccessKey": string;
    "mfaDevice": string;
}

/**
 * UpdateInfo is what the settings screen shows after a check.
 */
export interface UpdateInfo {
    "enabled": boolean;
    "currentVersion": string;
    "available": boolean;
    "version"?: string;
    "notes"?: string;
    "state": string;
}
