// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RolleService exposes the application to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../internal/core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discover$0 from "../../internal/discover/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddAWSSSO registers an IAM Identity Center portal.
 */
export function AddAWSSSO(alias: string, startURL: string, region: string): $CancellablePromise<core$0.Integration> {
    return $Call.ByID(407140754, alias, startURL, region);
}

/**
 * AddAssumeRole creates a role-chaining session.
 */
export function AddAssumeRole($in: app$0.AddAssumeRoleInput): $CancellablePromise<core$0.Session> {
    return $Call.ByID(2070632444, $in);
}

/**
 * AddAzure registers an Entra ID tenant.
 */
export function AddAzure(alias: string, tenantID: string): $CancellablePromise<core$0.Integration> {
    return $Call.ByID(613093005, alias, tenantID);
}

/**
 * AddGCP registers gcloud credentials and discovers projects.
 */
export function AddGCP(alias: string): $CancellablePromise<core$0.Session[] | null> {
    return $Call.ByID(2235238980, alias);
}

/**
 * AddGCPImpersonation creates a service account impersonation session.
 */
export function AddGCPImpersonation($in: app$0.AddGCPImpersonationInput): $CancellablePromise<core$0.Session> {
    return $Call.ByID(1206622824, $in);
}

/**
 * AddIAMUser creates a session backed by an access key.
 */
export function AddIAMUser($in: $models.IAMUserInput): $CancellablePromise<core$0.Session> {
    return $Call.ByID(3912635692, $in);
}

/**
 * AzureLogin opens the browser sign-in, then discovers subscriptions.
 */
export function AzureLogin(ref: string): $CancellablePromise<core$0.Session[] | null> {
    return $Call.ByID(577656563, ref);
}

/**
 * AzureLogout signs out of a tenant.
 */
export function AzureLogout(ref: string): $CancellablePromise<void> {
    return $Call.ByID(3688204768, ref);
}

/**
 * CheckForUpdates asks the release feed for a newer version.
 */
export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(4055142114);
}

/**
 * CompleteOnboarding marks the walkthrough as done.
 */
export function CompleteOnboarding(): $CancellablePromise<void> {
    return $Call.ByID(1536131245);
}

/**
 * Credentials returns fresh credentials for an active session.
 */
export function Credentials(ref: string): $CancellablePromise<core$0.Credentials> {
    return $Call.ByID(34508111, ref);
}

/**
 * DevMode reports whether in-app dev tools are compiled in.
 */
export function DevMode(): $CancellablePromise<boolean> {
    return $Call.ByID(571411941);
}

/**
 * Discover reports identities other tools already configured on this machine.
 */
export function Discover(): $CancellablePromise<discover$0.Result> {
    return $Call.ByID(3579054332);
}

/**
 * EnvText returns shell export lines for an active session.
 */
export function EnvText(ref: string): $CancellablePromise<string> {
    return $Call.ByID(3197417657, ref);
}

/**
 * GCPStatus checks for local gcloud credentials and the gcloud CLI.
 */
export function GCPStatus(): $CancellablePromise<$models.GCPStatus> {
    return $Call.ByID(4139794677);
}

/**
 * GCloudLogin runs the gcloud Application Default Credentials login, which
 * opens the browser. Blocks until gcloud finishes.
 */
export function GCloudLogin(): $CancellablePromise<void> {
    return $Call.ByID(3266413918);
}

/**
 * ImportAWSSSO registers a portal from the AWS CLI config, reusing its token when valid.
 */
export function ImportAWSSSO(alias: string, startURL: string, region: string): $CancellablePromise<app$0.ImportResult> {
    return $Call.ByID(168745974, alias, startURL, region);
}

/**
 * Info returns version and file locations for the settings screen.
 */
export function Info(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(135200251);
}

/**
 * InstallUpdate downloads, verifies, and installs the latest release, then
 * prompts through the updater window to restart.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(4116835583);
}

/**
 * OpenConsole opens the AWS console for a session in the browser.
 */
export function OpenConsole(ref: string): $CancellablePromise<void> {
    return $Call.ByID(160202760, ref);
}

/**
 * OpenTerminal opens the user's terminal with the session's environment ready.
 */
export function OpenTerminal(ref: string): $CancellablePromise<void> {
    return $Call.ByID(1037758735, ref);
}

/**
 * OpenURL opens a link in the default browser.
 */
export function OpenURL(u: string): $CancellablePromise<void> {
    return $Call.ByID(3697858276, u);
}

/**
 * ProfileName returns the AWS profile a session writes.
 */
export function ProfileName(ref: string): $CancellablePromise<string> {
    return $Call.ByID(816494467, ref);
}

/**
 * RemoveIntegration deletes a portal and its sessions.
 */
export function RemoveIntegration(ref: string): $CancellablePromise<void> {
    return $Call.ByID(2699167779, ref);
}

/**
 * RemoveSession deletes a session.
 */
export function RemoveSession(ref: string): $CancellablePromise<void> {
    return $Call.ByID(3021866781, ref);
}

/**
 * RenameIntegration changes an integration's display name.
 */
export function RenameIntegration(ref: string, alias: string): $CancellablePromise<void> {
    return $Call.ByID(4221515021, ref, alias);
}

/**
 * RenameSession changes a session's name.
 */
export function RenameSession(ref: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3621296503, ref, name);
}

/**
 * ReplayOnboarding shows the walkthrough again without removing sessions.
 */
export function ReplayOnboarding(): $CancellablePromise<void> {
    return $Call.ByID(536385161);
}

/**
 * Reset removes every session, integration, secret, cached credential, and
 * Rolle-owned AWS profile. The UI confirms before calling this.
 */
export function Reset(): $CancellablePromise<void> {
    return $Call.ByID(4248150206);
}

/**
 * SSOLogout signs out of a portal.
 */
export function SSOLogout(ref: string): $CancellablePromise<void> {
    return $Call.ByID(816108696, ref);
}

/**
 * SetFavorite pins or unpins a session.
 */
export function SetFavorite(ref: string, favorite: boolean): $CancellablePromise<void> {
    return $Call.ByID(141333789, ref, favorite);
}

/**
 * Settings returns the effective user preferences.
 */
export function Settings(): $CancellablePromise<core$0.Settings> {
    return $Call.ByID(1191667682);
}

/**
 * Start activates a session. mfaCode may be empty.
 */
export function Start(ref: string, mfaCode: string): $CancellablePromise<core$0.Credentials> {
    return $Call.ByID(62047909, ref, mfaCode);
}

/**
 * StartSSOLogin begins the device flow and opens the browser. Call WaitSSOLogin next.
 */
export function StartSSOLogin(ref: string): $CancellablePromise<$models.DeviceLogin> {
    return $Call.ByID(3044344761, ref);
}

/**
 * Stop deactivates a session.
 */
export function Stop(ref: string): $CancellablePromise<void> {
    return $Call.ByID(95473271, ref);
}

/**
 * SyncAzure rediscovers subscriptions.
 */
export function SyncAzure(ref: string): $CancellablePromise<core$0.Session[] | null> {
    return $Call.ByID(4041223311, ref);
}

/**
 * SyncGCP rediscovers projects.
 */
export function SyncGCP(ref: string): $CancellablePromise<core$0.Session[] | null> {
    return $Call.ByID(2268681726, ref);
}

/**
 * SyncSSO rediscovers roles.
 */
export function SyncSSO(ref: string): $CancellablePromise<core$0.Session[] | null> {
    return $Call.ByID(3979444731, ref);
}

/**
 * UpdateSettings stores preferences.
 */
export function UpdateSettings($in: core$0.Settings): $CancellablePromise<core$0.Settings> {
    return $Call.ByID(2682712267, $in);
}

/**
 * WaitSSOLogin blocks until the user approves, then discovers roles.
 */
export function WaitSSOLogin(ref: string): $CancellablePromise<core$0.Session[] | null> {
    return $Call.ByID(1083657062, ref);
}

/**
 * Workspace returns the workspace with session statuses reconciled.
 */
export function Workspace(): $CancellablePromise<core$0.Workspace | null> {
    return $Call.ByID(1576073332);
}
