// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RolleService exposes the application to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../internal/core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddAWSSSO registers an IAM Identity Center portal.
 */
export function AddAWSSSO(alias: string, startURL: string, region: string): $CancellablePromise<core$0.Integration> {
    return $Call.ByID(407140754, alias, startURL, region);
}

/**
 * AddAssumeRole creates a role-chaining session.
 */
export function AddAssumeRole($in: app$0.AddAssumeRoleInput): $CancellablePromise<core$0.Session> {
    return $Call.ByID(2070632444, $in);
}

/**
 * AddIAMUser creates a session backed by an access key.
 */
export function AddIAMUser($in: $models.IAMUserInput): $CancellablePromise<core$0.Session> {
    return $Call.ByID(3912635692, $in);
}

/**
 * CompleteOnboarding marks the walkthrough as done.
 */
export function CompleteOnboarding(): $CancellablePromise<void> {
    return $Call.ByID(1536131245);
}

/**
 * Credentials returns fresh credentials for an active session.
 */
export function Credentials(ref: string): $CancellablePromise<core$0.Credentials> {
    return $Call.ByID(34508111, ref);
}

/**
 * OpenConsole opens the AWS console for a session in the browser.
 */
export function OpenConsole(ref: string): $CancellablePromise<void> {
    return $Call.ByID(160202760, ref);
}

/**
 * OpenURL opens a link in the default browser.
 */
export function OpenURL(u: string): $CancellablePromise<void> {
    return $Call.ByID(3697858276, u);
}

/**
 * ProfileName returns the AWS profile a session writes.
 */
export function ProfileName(ref: string): $CancellablePromise<string> {
    return $Call.ByID(816494467, ref);
}

/**
 * RemoveIntegration deletes a portal and its sessions.
 */
export function RemoveIntegration(ref: string): $CancellablePromise<void> {
    return $Call.ByID(2699167779, ref);
}

/**
 * RemoveSession deletes a session.
 */
export function RemoveSession(ref: string): $CancellablePromise<void> {
    return $Call.ByID(3021866781, ref);
}

/**
 * SSOLogout signs out of a portal.
 */
export function SSOLogout(ref: string): $CancellablePromise<void> {
    return $Call.ByID(816108696, ref);
}

/**
 * Start activates a session. mfaCode may be empty.
 */
export function Start(ref: string, mfaCode: string): $CancellablePromise<core$0.Credentials> {
    return $Call.ByID(62047909, ref, mfaCode);
}

/**
 * StartSSOLogin begins the device flow and opens the browser. Call WaitSSOLogin next.
 */
export function StartSSOLogin(ref: string): $CancellablePromise<$models.DeviceLogin> {
    return $Call.ByID(3044344761, ref);
}

/**
 * Stop deactivates a session.
 */
export function Stop(ref: string): $CancellablePromise<void> {
    return $Call.ByID(95473271, ref);
}

/**
 * SyncSSO rediscovers roles.
 */
export function SyncSSO(ref: string): $CancellablePromise<core$0.Session[] | null> {
    return $Call.ByID(3979444731, ref);
}

/**
 * WaitSSOLogin blocks until the user approves, then discovers roles.
 */
export function WaitSSOLogin(ref: string): $CancellablePromise<core$0.Session[] | null> {
    return $Call.ByID(1083657062, ref);
}

/**
 * Workspace returns the workspace with session statuses reconciled.
 */
export function Workspace(): $CancellablePromise<core$0.Workspace | null> {
    return $Call.ByID(1576073332);
}
