// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RolleService exposes the application to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../internal/app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../internal/core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discover$0 from "../../internal/discover/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddAWSSSO registers an IAM Identity Center portal.
 */
export function AddAWSSSO(alias: string, startURL: string, region: string): $CancellablePromise<core$0.Integration> {
    return $Call.ByID(407140754, alias, startURL, region);
}

/**
 * AddAssumeRole creates a role-chaining session.
 */
export function AddAssumeRole($in: app$0.AddAssumeRoleInput): $CancellablePromise<core$0.Session> {
    return $Call.ByID(2070632444, $in);
}

/**
 * AddAzure registers an Entra ID tenant.
 */
export function AddAzure(alias: string, tenantID: string): $CancellablePromise<core$0.Integration> {
    return $Call.ByID(613093005, alias, tenantID);
}

/**
 * AddGCP registers gcloud credentials and discovers projects.
 */
export function AddGCP(alias: string): $CancellablePromise<core$0.Session[] | null> {
    return $Call.ByID(2235238980, alias);
}

/**
 * AddGCPImpersonation creates a service account impersonation session.
 */
export function AddGCPImpersonation($in: app$0.AddGCPImpersonationInput): $CancellablePromise<core$0.Session> {
    return $Call.ByID(1206622824, $in);
}

/**
 * AddIAMUser creates a session backed by an access key.
 */
export function AddIAMUser($in: $models.IAMUserInput): $CancellablePromise<core$0.Session> {
    return $Call.ByID(3912635692, $in);
}

/**
 * AddTag creates a sidebar tag.
 */
export function AddTag(tag: core$0.Tag): $CancellablePromise<void> {
    return $Call.ByID(2166625714, tag);
}

/**
 * AzureLogin opens the browser sign-in, then discovers subscriptions.
 */
export function AzureLogin(ref: string): $CancellablePromise<core$0.Session[] | null> {
    return $Call.ByID(577656563, ref);
}

/**
 * AzureLogout signs out of a tenant.
 */
export function AzureLogout(ref: string): $CancellablePromise<void> {
    return $Call.ByID(3688204768, ref);
}

/**
 * CLIStatus reports whether the bundled rolle command is on the PATH.
 */
export function CLIStatus(): $CancellablePromise<$models.CLIStatus> {
    return $Call.ByID(3736051989);
}

/**
 * CancelSSOLogin abandons a login that WaitSSOLogin is waiting on.
 */
export function CancelSSOLogin(ref: string): $CancellablePromise<void> {
    return $Call.ByID(596805525, ref);
}

/**
 * CheckForUpdates asks the release feed for a newer version.
 */
export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(4055142114);
}

/**
 * CompleteOnboarding marks the walkthrough as done.
 */
export function CompleteOnboarding(): $CancellablePromise<void> {
    return $Call.ByID(1536131245);
}

/**
 * DemoMode reports whether this process runs on fictional data.
 */
export function DemoMode(): $CancellablePromise<boolean> {
    return $Call.ByID(934183271);
}

/**
 * DevMode reports whether in-app dev tools are compiled in.
 */
export function DevMode(): $CancellablePromise<boolean> {
    return $Call.ByID(571411941);
}

/**
 * Discover reports identities other tools already configured on this machine.
 */
export function Discover(): $CancellablePromise<discover$0.Result> {
    return $Call.ByID(3579054332);
}

/**
 * EnvText returns shell export lines for an active session.
 */
export function EnvText(ref: string): $CancellablePromise<string> {
    return $Call.ByID(3197417657, ref);
}

/**
 * ExportSupportBundle writes the redacted support zip to the Downloads folder,
 * shows it in the file manager, and returns its path.
 */
export function ExportSupportBundle(): $CancellablePromise<string> {
    return $Call.ByID(2085165976);
}

/**
 * GCPStatus checks for local gcloud credentials and the gcloud CLI.
 */
export function GCPStatus(): $CancellablePromise<$models.GCPStatus> {
    return $Call.ByID(4139794677);
}

/**
 * GCloudLogin runs the gcloud Application Default Credentials login, which
 * opens the browser. Blocks until gcloud finishes.
 */
export function GCloudLogin(): $CancellablePromise<void> {
    return $Call.ByID(3266413918);
}

/**
 * ImportAWSSSO registers a portal from the AWS CLI config, reusing its token when valid.
 */
export function ImportAWSSSO(alias: string, startURL: string, region: string): $CancellablePromise<app$0.ImportResult> {
    return $Call.ByID(168745974, alias, startURL, region);
}

/**
 * ImportLeappSessions recreates IAM users and chained roles from a Leapp workspace.
 */
export function ImportLeappSessions(): $CancellablePromise<app$0.LeappImportResult> {
    return $Call.ByID(2452436981);
}

/**
 * Info returns version and file locations for the settings screen.
 */
export function Info(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(135200251);
}

/**
 * InstallCLI puts the command on the PATH. macOS links the bundle's helper
 * into /usr/local/bin and asks for an administrator password once when the
 * directory refuses. Windows and Linux write the embedded command to a user
 * directory; Windows adds that directory to the user's PATH.
 */
export function InstallCLI(): $CancellablePromise<$models.CLIStatus> {
    return $Call.ByID(904278096);
}

/**
 * InstallUpdate downloads, verifies, and installs the latest release, then
 * prompts through the updater window to restart.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(4116835583);
}

/**
 * MoveTag puts a tag at index in the sidebar order.
 */
export function MoveTag(name: string, index: number): $CancellablePromise<void> {
    return $Call.ByID(1990271286, name, index);
}

/**
 * OpenConsole opens the AWS console for a session in the browser.
 */
export function OpenConsole(ref: string): $CancellablePromise<void> {
    return $Call.ByID(160202760, ref);
}

/**
 * OpenTerminal opens the user's terminal with the session's environment ready.
 */
export function OpenTerminal(ref: string): $CancellablePromise<void> {
    return $Call.ByID(1037758735, ref);
}

/**
 * OpenURL opens a link in the default browser.
 */
export function OpenURL(u: string): $CancellablePromise<void> {
    return $Call.ByID(3697858276, u);
}

/**
 * PendingUpdate returns the release the last background check found, or nil.
 * The frontend calls it on mount to catch a check that ran before it loaded.
 */
export function PendingUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(1900173335);
}

/**
 * ProfileShadow returns the file, in display form, whose static keys tools
 * read instead of a profile of that name, or "". The window offers to remove
 * those keys, so a profile that another tool configures in the config file
 * reports "".
 */
export function ProfileShadow(name: string): $CancellablePromise<string> {
    return $Call.ByID(4258961860, name);
}

/**
 * Relaunch starts a second copy of this app, on fictional data when demo is
 * true and on the real workspace otherwise, then quits this one. Dev builds only.
 */
export function Relaunch(demo: boolean): $CancellablePromise<void> {
    return $Call.ByID(3931302737, demo);
}

/**
 * RemoveIntegration deletes a portal and its sessions.
 */
export function RemoveIntegration(ref: string): $CancellablePromise<void> {
    return $Call.ByID(2699167779, ref);
}

/**
 * RemoveSession deletes a session.
 */
export function RemoveSession(ref: string): $CancellablePromise<void> {
    return $Call.ByID(3021866781, ref);
}

/**
 * RemoveStaticProfile deletes the static keys of one section of the shared
 * credentials file.
 */
export function RemoveStaticProfile(name: string): $CancellablePromise<void> {
    return $Call.ByID(2217434922, name);
}

/**
 * RemoveTag deletes a tag and takes it off every session.
 */
export function RemoveTag(name: string): $CancellablePromise<void> {
    return $Call.ByID(2843774673, name);
}

/**
 * RenameIntegration changes an integration's display name.
 */
export function RenameIntegration(ref: string, alias: string): $CancellablePromise<void> {
    return $Call.ByID(4221515021, ref, alias);
}

/**
 * RenameSession changes a session's name.
 */
export function RenameSession(ref: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3621296503, ref, name);
}

/**
 * ReplayOnboarding shows the walkthrough again without removing sessions.
 */
export function ReplayOnboarding(): $CancellablePromise<void> {
    return $Call.ByID(536385161);
}

/**
 * Reset removes every session, integration, secret, cached credential, and
 * rolle-owned AWS profile. The UI confirms before calling this.
 */
export function Reset(): $CancellablePromise<void> {
    return $Call.ByID(4248150206);
}

/**
 * SSOLogout signs out of a portal.
 */
export function SSOLogout(ref: string): $CancellablePromise<void> {
    return $Call.ByID(816108696, ref);
}

/**
 * SetAccountHidden hides or shows every role of an Identity Center account.
 */
export function SetAccountHidden(integrationID: string, accountID: string, hidden: boolean): $CancellablePromise<void> {
    return $Call.ByID(3353278944, integrationID, accountID, hidden);
}

/**
 * SetAlias names an Identity Center account or permission set in every
 * session name. An empty alias clears it.
 */
export function SetAlias(kind: string, key: string, alias: string): $CancellablePromise<void> {
    return $Call.ByID(3846202439, kind, key, alias);
}

/**
 * SetFavorite pins or unpins a session.
 */
export function SetFavorite(ref: string, favorite: boolean): $CancellablePromise<void> {
    return $Call.ByID(141333789, ref, favorite);
}

/**
 * SetHidden hides or shows a session.
 */
export function SetHidden(ref: string, hidden: boolean): $CancellablePromise<void> {
    return $Call.ByID(2816945065, ref, hidden);
}

/**
 * SetProfile sets the AWS profile name for a session. Empty restores the default.
 */
export function SetProfile(ref: string, profile: string): $CancellablePromise<void> {
    return $Call.ByID(1410044798, ref, profile);
}

/**
 * SetRegion changes an AWS session's region.
 */
export function SetRegion(ref: string, region: string): $CancellablePromise<void> {
    return $Call.ByID(658228237, ref, region);
}

/**
 * SetSessionTag adds a tag to a session or takes it off.
 */
export function SetSessionTag(ref: string, tag: string, on: boolean): $CancellablePromise<void> {
    return $Call.ByID(423614861, ref, tag, on);
}

/**
 * Settings returns the effective user preferences.
 */
export function Settings(): $CancellablePromise<core$0.Settings> {
    return $Call.ByID(1191667682);
}

/**
 * Start activates a session. mfaCode may be empty.
 */
export function Start(ref: string, mfaCode: string): $CancellablePromise<core$0.Credentials> {
    return $Call.ByID(62047909, ref, mfaCode);
}

/**
 * StartSSOLogin begins the browser sign-in and opens the page. Call WaitSSOLogin next.
 */
export function StartSSOLogin(ref: string): $CancellablePromise<$models.DeviceLogin> {
    return $Call.ByID(3044344761, ref);
}

/**
 * StaticProfiles lists the sections of ~/.aws/credentials that hold static
 * keys, with the file's path.
 */
export function StaticProfiles(): $CancellablePromise<app$0.StaticKeys> {
    return $Call.ByID(3473546599);
}

/**
 * Stop deactivates a session.
 */
export function Stop(ref: string): $CancellablePromise<void> {
    return $Call.ByID(95473271, ref);
}

/**
 * SupportURL is the GitHub bug report form with version and platform filled in.
 */
export function SupportURL(): $CancellablePromise<string> {
    return $Call.ByID(2961329235);
}

/**
 * SyncAzure rediscovers subscriptions.
 */
export function SyncAzure(ref: string): $CancellablePromise<core$0.Session[] | null> {
    return $Call.ByID(4041223311, ref);
}

/**
 * SyncGCP rediscovers projects.
 */
export function SyncGCP(ref: string): $CancellablePromise<core$0.Session[] | null> {
    return $Call.ByID(2268681726, ref);
}

/**
 * SyncSSO rediscovers roles.
 */
export function SyncSSO(ref: string): $CancellablePromise<core$0.Session[] | null> {
    return $Call.ByID(3979444731, ref);
}

/**
 * UnhideAll shows every hidden session again.
 */
export function UnhideAll(): $CancellablePromise<void> {
    return $Call.ByID(3014630259);
}

/**
 * UninstallCLI removes what Install made: the link on macOS, the user copy on
 * Windows and Linux. A command installed another way is left alone.
 */
export function UninstallCLI(): $CancellablePromise<void> {
    return $Call.ByID(1017279095);
}

/**
 * UpdateSettings stores preferences. The update ticker reads AutoUpdateOff on
 * every tick, so the change applies without a restart.
 */
export function UpdateSettings($in: core$0.Settings): $CancellablePromise<core$0.Settings> {
    return $Call.ByID(2682712267, $in);
}

/**
 * UpdateTag changes a tag's name, color, or icon.
 */
export function UpdateTag(name: string, tag: core$0.Tag): $CancellablePromise<void> {
    return $Call.ByID(3890086686, name, tag);
}

/**
 * WaitSSOLogin blocks until the user approves, then discovers roles.
 */
export function WaitSSOLogin(ref: string): $CancellablePromise<core$0.Session[] | null> {
    return $Call.ByID(1083657062, ref);
}

/**
 * Workspace returns the stored workspace. Renewals run on the background
 * ticker in main.go, which saves and so emits EventWorkspaceChanged; the UI
 * must not wait on the network to paint.
 */
export function Workspace(): $CancellablePromise<core$0.Workspace | null> {
    return $Call.ByID(1576073332);
}
