// Command regions writes the AWS region list of the desktop picker from the
// partition table that ships with the pinned aws-sdk-go-v2 module. Renovate
// bumps the module, so the list follows AWS without a hand edit.
//
// Run from the repository root: go run ./tools/regions [-check]
// -check compares the file with what the generator would write and fails on
// a difference, for CI.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const output = "apps/desktop/frontend/src/lib/aws-regions.ts"

// partitions are the ones rolle resolves hosts for. The ISO partitions and
// the European Sovereign Cloud are left out until rolle supports them.
var partitions = map[string]bool{"aws": true, "aws-cn": true, "aws-us-gov": true}

// groups maps the area that starts an SDK description, "US East (Ohio)",
// onto a picker group. The order of groupOrder is the order in the picker.
var groups = map[string]string{
	"US East":       "United States",
	"US West":       "United States",
	"Canada":        "Canada",
	"Canada West":   "Canada",
	"Mexico":        "Mexico",
	"Europe":        "Europe",
	"Asia Pacific":  "Asia Pacific",
	"Middle East":   "Middle East & Africa",
	"Israel":        "Middle East & Africa",
	"Africa":        "Middle East & Africa",
	"South America": "South America",
	"China":         "China",
	"AWS GovCloud":  "AWS GovCloud (US)",
}

var groupOrder = []string{
	"United States", "Canada", "Mexico", "Europe", "Asia Pacific",
	"Middle East & Africa", "South America", "China", "AWS GovCloud (US)",
}

// names replaces an SDK name that lost its accent in ASCII.
var names = map[string]string{"sa-east-1": "São Paulo"}

type region struct{ id, name string }

func main() {
	check := flag.Bool("check", false, "compare the file with the generated list instead of writing it")
	flag.Parse()
	want, err := generate()
	if err != nil {
		fail(err)
	}
	if *check {
		have, err := os.ReadFile(output)
		if err != nil {
			fail(err)
		}
		if !bytes.Equal(have, want) {
			fail(fmt.Errorf("%s is out of date with the AWS SDK's partition table; run `mise run regions`", output))
		}
		return
	}
	if err := os.WriteFile(output, want, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "regions:", err)
	os.Exit(1)
}

// generate renders the TypeScript file from the SDK's partition table.
func generate() ([]byte, error) {
	table, err := partitionsFile()
	if err != nil {
		return nil, err
	}
	byGroup, err := regionsByGroup(table)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("// Generated by tools/regions from the aws-sdk-go-v2 partition table. Do not\n")
	b.WriteString("// edit; run `mise run regions` after a module bump.\n\n")
	b.WriteString("/** AWS regions, grouped for the picker. Identity Center portals live in one of these. */\n")
	b.WriteString("export const AWS_REGIONS: { group: string; regions: { id: string; name: string }[] }[] = [\n")
	for _, group := range groupOrder {
		regions := byGroup[group]
		if len(regions) == 0 {
			continue
		}
		// One region fits on a line, as the formatter would lay it out.
		if len(regions) == 1 {
			fmt.Fprintf(&b, "  { group: %q, regions: [{ id: %q, name: %q }] },\n", group, regions[0].id, regions[0].name)
			continue
		}
		fmt.Fprintf(&b, "  {\n    group: %q,\n    regions: [\n", group)
		for _, r := range regions {
			fmt.Fprintf(&b, "      { id: %q, name: %q },\n", r.id, r.name)
		}
		b.WriteString("    ],\n  },\n")
	}
	b.WriteString("];\n")
	return b.Bytes(), nil
}

// partitionsFile reads partitions.json from the pinned module in the cache.
func partitionsFile() ([]byte, error) {
	out, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", "github.com/aws/aws-sdk-go-v2").Output()
	if err != nil {
		return nil, fmt.Errorf("locate aws-sdk-go-v2: %w", err)
	}
	dir := strings.TrimSpace(string(out))
	return os.ReadFile(filepath.Join(dir, "internal", "endpoints", "awsrulesfn", "partitions.json"))
}

// regionsByGroup parses the table into picker groups, sorted by region code.
func regionsByGroup(table []byte) (map[string][]region, error) {
	var doc struct {
		Partitions []struct {
			ID      string `json:"id"`
			Regions map[string]struct {
				Description string `json:"description"`
			} `json:"regions"`
		} `json:"partitions"`
	}
	if err := json.Unmarshal(table, &doc); err != nil {
		return nil, fmt.Errorf("parse partitions.json: %w", err)
	}
	byGroup := map[string][]region{}
	for _, p := range doc.Partitions {
		if !partitions[p.ID] {
			continue
		}
		for id, r := range p.Regions {
			// The partition's own pseudo region is not a place.
			if strings.HasSuffix(id, "-global") {
				continue
			}
			area, name, ok := splitDescription(r.Description)
			if !ok {
				return nil, fmt.Errorf("%s: description %q is not \"Area (Name)\"", id, r.Description)
			}
			group, ok := groups[area]
			if !ok {
				return nil, fmt.Errorf("%s: area %q has no picker group; add it to tools/regions", id, area)
			}
			if n, ok := names[id]; ok {
				name = n
			}
			byGroup[group] = append(byGroup[group], region{id: id, name: name})
		}
	}
	for _, regions := range byGroup {
		sort.Slice(regions, func(i, j int) bool { return regions[i].id < regions[j].id })
	}
	return byGroup, nil
}

// splitDescription turns "Asia Pacific (Malaysia)" into its area and name.
func splitDescription(d string) (area, name string, ok bool) {
	open := strings.LastIndex(d, " (")
	if open < 0 || !strings.HasSuffix(d, ")") {
		return "", "", false
	}
	return d[:open], d[open+2 : len(d)-1], true
}
