// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StaticKey is one masked key line of a profile.
 */
export interface StaticKey {
    "name": string;

    /**
     * Preview shows the start of an access key ID and nothing of a secret.
     */
    "preview": string;
}

/**
 * StaticProfile is a profile of the shared credentials file that holds
 * static keys.
 */
export interface StaticProfile {
    "name": string;

    /**
     * Keys are the static key lines, with values masked for display.
     */
    "keys": StaticKey[] | null;

    /**
     * Imported is true when a rolle session holds the same access key. The
     * app layer sets it; StaticProfiles leaves it false.
     */
    "imported": boolean;
}
